language: ruby
script: bundle exec rake test_$DB
rvm:
  - jruby-18mode
  - jruby-19mode
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite3
  # derby - tested with test_jndi
  #- DB=derby
  - DB=h2
  - DB=hsqldb
  - DB=jndi
  - DB=jdbc
gemfile:
  - gemfiles/rails23.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
branches:
  only:
    - master
    - 1-2-stable
matrix:
  allow_failures:
    # probably fine to allow in 1.3.x :
    #- gemfile: gemfiles/rails23.gemfile
    # NOTE: not sure why it can't connect :
    - env: DB=jdbc
